name: 'AfterNoonClockIn'
 
on:
  #push:  ##打开这里表示一推送即执行一次
  schedule:
     ## UTC时间比我们晚8个小时，此处实际执行时间是 9:46 + 8:00 = 17:46
    - cron: '46 09 * * 1-5'

jobs:
  afterNoon:
    runs-on: ubuntu-latest
    steps:
    # 首先copy git仓库到虚拟机上,然后执行
      - name: 'Checkout codes'
        uses: actions/checkout@v1
    # 执行仓库中的脚本文件
      - name: 'Run Shell'
        run: bash ./clock_in.sh
      # 获取格式化的日期并存入GitHub内置的环境变量中
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      # 使用现成的发送邮箱的GitHub action来发送邮件
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          # 这些是发送邮件需要配置的参数，更多详细的说明请访问具体的仓库
          server_address: smtp.qq.com
          server_port: 465
          # 这些sectret的环境变量需要配置在setting中的secret下
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 打卡结果(${{env.REPORT_DATE}})
          body: file://result.txt
          to: 2330996055@qq.com
          from: GitHub Actions
          content_type: text/html
